env:
  global:
    - CC_TEST_REPORTER_ID=19b2a7d66f2ba914b2ae9365bdfe09c838458e0c7d8a0d0c95f4d44d58b73dde
language: node_js
node_js:
  - '10'
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://bradwindy.github.io/angular-ci-test/
after_script:
  - ls -a
  - ./cc-test-reporter format-coverage -t lcov -o codeclimate.frontend.json coverage/angular-ci/lcov.info
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
deploy:
  provider: pages
  local_dir: dist/angular-ci
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
